title: Mapping Language
author: Andrew Weymouth
email: aweymo@uw.edu
description: >-
  Representation of  Immigrant Communities in the Pacific Northwest, 1880-1930
baseurl: "/cs_land" # the subpath of your site, e.g. /blog
url: "https://aweymo.github.io/cs_land" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

