---
title: Mapping Language
author: Andrew Weymouth
email: aweymo@uw.edu
description: Representation of  Immigrant Communities in the Pacific Northwest, 1880-1930
baseurl: "/cs_land"
url: https://aweymo.github.io/cs_land
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
menu:
  main:
    weight: 1
